name: Release Docker Image

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set TAG variable
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          GIT_TAG=${GITHUB_REF#refs/tags/}
          TAG="${SHORT_SHA}-${GIT_TAG}"
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "Tag to use: $TAG"

      - name: Build only services with build context
        run: |
          echo "🔧 Building with tag: $TAG"
          docker compose -f docker-compose.yml -f docker-compose.dev.yml build runtime-sdv

      - name: Tag image for GHCR
        run: |
          IMAGE_ID=$(docker compose -f docker-compose.yml -f docker-compose.dev.yml images -q runtime-sdv)
          docker tag $IMAGE_ID ghcr.io/${{ github.repository_owner }}/runtime-sdv:$TAG

      - name: Push image to GitHub Container Registry
        run: |
          echo "🚀 Pushing image: ghcr.io/${{ github.repository_owner }}/runtime-sdv:$TAG"
          docker push ghcr.io/${{ github.repository_owner }}/runtime-sdv:$TAG

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
