name: Release Docker Image

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        id: docker_login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set TAG variable
        id: vars
        run: |
          GIT_TAG=${GITHUB_REF#refs/tags/}
          TAG="${GIT_TAG}"
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "TAG=$TAG"  # output for debug
          echo "::set-output name=TAG::$TAG"  # deprecated but kept for backward compatibility

      - name: Build and optionally push multi-arch image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ steps.docker_login.outcome == 'success' }}
          tags: ghcr.io/${{ github.repository_owner }}/sdv-runtime:${{ env.TAG }}
          platforms: linux/amd64,linux/arm64
