name: Release Docker Image

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        id: ghcr_login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from tag
        id: vars
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build and push multi-arch image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/sdv-runtime:${{ steps.vars.outputs.VERSION }}
          platforms: linux/amd64,linux/arm64

      - name: Export amd64 image as tar
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --output type=docker,dest=sdv-runtime-amd64.tar \
            -t ghcr.io/${{ github.repository_owner }}/sdv-runtime:${{ steps.vars.outputs.VERSION }} .

      - name: Export arm64 image as tar
        run: |
          docker buildx build \
            --platform linux/arm64 \
            --output type=docker,dest=sdv-runtime-arm64.tar \
            -t ghcr.io/${{ github.repository_owner }}/sdv-runtime:${{ steps.vars.outputs.VERSION }} .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload image tars to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            sdv-runtime-amd64.tar
            sdv-runtime-arm64.tar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}