name: Release Docker Image

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        continue-on-error: true
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version from tag
        id: vars
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create custom Docker builder
        continue-on-error: true
        run: |
          docker buildx create --driver docker-container \
            --driver-opt network=host \
            --driver-opt env.http_proxy=$https_proxy \
            --driver-opt env.https_proxy=$https_proxy \
            --name mybuilder \
            --platform "linux/amd64,linux/arm64" default || true
          docker buildx use mybuilder || true

      - name: Build and push image to Docker Hub
        continue-on-error: true
        run: |
          docker buildx build --push \
            --platform linux/amd64,linux/arm64 \
            -t boschvn/sdv-runtime:${{ steps.vars.outputs.VERSION }} \
            -f Dockerfile .

      - name: Save Docker image as tar
        continue-on-error: true
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --output type=docker,dest=sdv-runtime.tar \
            -t boschvn/sdv-runtime:${{ steps.vars.outputs.VERSION }} .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload image tar to GitHub Release
        continue-on-error: true
        uses: softprops/action-gh-release@v2
        with:
          files: sdv-runtime.tar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}