name: Release Docker Image

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version from tag
        id: vars
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build and push image to Docker Hub
        uses: docker/build-push-action@v5
        continue-on-error: true
        with:
          context: .
          push: true
          tags: boschvn/sdv-runtime:${{ steps.vars.outputs.VERSION }}
          platforms: linux/amd64,linux/arm64

      - name: Save Docker image as tar
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --output type=docker,dest=sdv-runtime.tar \
            -t boschvn/sdv-runtime:${{ steps.vars.outputs.VERSION }} .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload image tar to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: sdv-runtime.tar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}