name: Release Docker Image

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract version from tag
        id: vars
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build image (no push)
        id: build
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --output type=oci,dest=image.tar \
            -t boschvn/sdv-runtime:${{ steps.vars.outputs.VERSION }} .
        continue-on-error: true

      - name: Log in to DockerHub (optional)
        id: login
        if: steps.build.outcome == 'success'
        continue-on-error: true
        run: |
          if [ -n "${{ secrets.DOCKER_USERNAME }}" ] && [ -n "${{ secrets.DOCKER_PASSWORD }}" ]; then
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            echo "logged_in=true" >> $GITHUB_OUTPUT
          else
            echo "DockerHub credentials not set. Skipping login."
            echo "logged_in=false" >> $GITHUB_OUTPUT
          fi

      - name: Push image to Docker Hub
        if: steps.build.outcome == 'success' && steps.login.outputs.logged_in == 'true'
        run: |
          docker load -i image.tar
          docker push boschvn/sdv-runtime:${{ steps.vars.outputs.VERSION }}

      - name: Save Docker image as tar
        if: steps.build.outcome == 'success'
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --output type=docker,dest=sdv-runtime.tar \
            -t boschvn/sdv-runtime:${{ steps.vars.outputs.VERSION }} .

      - name: Upload image tar as artifact
        if: steps.build.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: sdv-runtime-tar
          path: sdv-runtime.tar

      - name: Create GitHub Release
        if: steps.build.outcome == 'success'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload image tar to GitHub Release
        if: steps.build.outcome == 'success'
        uses: softprops/action-gh-release@v2
        with:
          files: sdv-runtime.tar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
