name: Pull and Tag Multi-Arch Docker Image

on:
  workflow_dispatch:
    inputs:
      source_tag:
        description: 'The source image tag to pull'
        required: true
        default: 'latest'
      target_tag:
        description: 'The target image tag to push'
        required: true
        default: 'latest'

jobs:
  pull-and-tag-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Pull, tag, and push multi-arch Docker image
        run: |
          docker buildx imagetools create \
            --tag ${{ secrets.DOCKER_ORG }}/sdv-runtime:${{ github.event.inputs.target_tag }} \
            ${{ secrets.DOCKER_ORG }}/sdv-runtime:${{ github.event.inputs.source_tag }}

      - name: Verify pushed image
        run: |
          docker buildx imagetools inspect ${{ secrets.DOCKER_ORG }}/sdv-runtime:${{ github.event.inputs.target_tag }}